### ISSUE TITLE
Incorrect image size on 2nd vertical monitor

### ISSUE THREAD

**Issue by TotalTaxAmount** [LGFae/swww#369] opened 2024-10-15 03:02 UTC
When setting a wallpaper on my second monitor, swww does not set the wallpaper on the whole screen:
![image](https://github.com/user-attachments/assets/a4a3aa13-0ce1-4b35-b12a-a64805980606)

Output of `swww query`:
```
HDMI-A-1: 2560x1440, scale: 1, currently displaying: image: /home/totaltaxamount/nix/dots/swww/desktop/2nd.jpg
DP-1: 3440x1440, scale: 1, currently displaying: image: /home/totaltaxamount/nix/dots/swww/desktop/ultrawide.png
```

The resolution is correct here. Setting `--resize=no` shows a black square in the same posiotn, `--resize=crop` is the same as the image above, and `--resize=fit` shows the full image with black bars:
![image](https://github.com/user-attachments/assets/25b658bd-ee21-454a-ac70-b8bb312b5c51)

**Comment by kRHYME7** [comment] 2024-10-17 14:02
@TotalTaxAmount are you using the main/master branch or many have reported that the master build already fixes the issue.

**Comment by bigmcnuggets** [comment] 2024-10-23 19:33
I have the same issue. Im using the swww available in the Arch package manager.

**Comment by bigmcnuggets** [comment] 2024-10-23 19:40
> I have the same issue. Im using the swww available in the Arch package manager, which is 0.9.5-2

Ok I switched to swww-git in the AUR, problem instantly solved, no further tinkering!

thanks for the main branch recommendation @kRHYME7 !

**Comment by TotalTaxAmount** [comment] 2024-10-23 20:18
Happened to me swww from the latest nixpkgs. Running `swww --version` gives `swww 0.9.5`.

**Comment by LGFae** [comment] 2024-10-27 14:16
This is a duplicate of #351, so I will be closing this one. Note that,  as some have mentioned, this is most likely already fixed in the latest `git` version, that is still unreleased.

**Closed by LGFae** 2024-10-27 14:16 UTC
Labels: duplicate, fixed in master
