### ISSUE TITLE
swww 0.9.3 doesn't correctly scale images on hidpi

### ISSUE THREAD

**Issue by nergdron** [LGFae/swww#281] opened 2024-04-16 14:24 UTC
I've been using swww for a few months under hyprland, and I've been really loving it. however, after logging in since the 0.9.3 release came out, it seems like something's broken on hidpi setups. swww is now only displaying my wallpaper in a 1920x1080 box in the center of my 4k monitor, and I can't seem to find any options to make it revert to the correct behaviour where it filled my screen.

this is on Arch, hyprland 0.39.0-1:

```sh
# hyprctl monitors
Monitor DP-2 (ID 0):
	3840x2160@239.99100 at 0x0
[...]
	scale: 1.25
	dpmsStatus: 1
	vrr: 1
	currentFormat: XRGB2101010
[...]

# swww query
DP-2: 1920x1080, scale: 2, currently displaying: image: /home/tessa/Pictures/wallpaper/desktop/cat-lying-on-its-back-uhd-4k-wallpaper.jpg

# gm identify /home/tessa/Pictures/wallpaper/desktop/cat-lying-on-its-back-uhd-4k-wallpaper.jpg
/home/tessa/Pictures/wallpaper/desktop/cat-lying-on-its-back-uhd-4k-wallpaper.jpg JPEG 3840x2160+0+0 DirectClass 8-bit 335.1Ki 0.000u 0m:0.000003s
```

this worked correctly with swww 0.9.2.

**Comment by vod3** [comment] 2024-04-16 14:25
the issue is right under yours: https://github.com/LGFae/swww/issues/279

**Comment by LGFae** [comment] 2024-04-16 16:35
Thanks, @vod3. I will be closing this for now as duplicate.

**Closed by LGFae** 2024-04-16 16:35 UTC
