### ISSUE TITLE
Ignoring laptop internal display

### ISSUE THREAD

**Issue by MrDuartePT** [LGFae/swww#186] opened 2023-11-26 09:08 UTC
Im using the script sww-randomize exemple from your repo and set Hyprland to start script ever time it restart (this way changing the walpaper).
```
hyprland.conf
------
#Exec 
(...)
exec-once = swww-daemon
exec = killall swww_randomize; $HOME/.config/hypr/swww_randomize $HOME/Pictures/wallpapers &
exec = pkill waybar; waybar
(...)
```
But for strange reason the internal laptop display get ignore, but the cache report the image was load
```
cache files
----
cat .cache/swww/HDMI-A-1
/home/mrduarte/Pictures/wallpapers/0049.jpg%                                                            
cat .cache/swww/eDP-1
/home/mrduarte/Pictures/wallpapers/0049.jpg% 
----
```
```
sww query
----
eDP-1: 1920x1080, scale: 1, currently displaying: color: 000000
HDMI-A-1: 1360x768, scale: 1, currently displaying: image: /home/mrduarte/Pictures/wallpapers/0049.jpg
----
```

Edit: Now I getting strange behaviour the laptop display change the image after the 5m timer as expected but if I reload Hyprland only the external display image change immediately and the image on both display only sync after the 5m timer elapses:
```
swww query after reload
----
eDP-1: 1920x1080, scale: 1, currently displaying: color: 000000
HDMI-A-1: 1360x768, scale: 1, currently displaying: image: /home/mrduarte/Pictures/wallpapers/0230.jpg
----
sww query after 5m
----
eDP-1: 1920x1080, scale: 1, currently displaying: image: /home/mrduarte/Pictures/wallpapers/0014.jpg
HDMI-A-1: 1360x768, scale: 1, currently displaying: image: /home/mrduarte/Pictures/wallpapers/0014.jpg
----

**Comment by MrDuartePT** [comment] 2023-11-26 09:40
Well if this not get fix is not a big deal at least is kinda working now

**Comment by MrDuartePT** [comment] 2023-12-01 16:08
Only when setting one image I have the same problem if Hyprland run the script:
```
hyprland.conf
------
#Exec 
(...)
exec-once = swww-daemon
exec-once = swaync
exec = $HOME/.config/hypr/set-displays-swayidle
(...)

cache files
----                                                         
cat .cache/swww/eDP-1
/home/mrduarte/Pictures/Lenovo Wallpapers/cyber_box.jpg%
----

sww query
----
eDP-1: 1920x1080, scale: 1, currently displaying: color: 000000
----
```
Desktop screenshot:
![image](https://github.com/Horus645/swww/assets/68701049/62f28f9a-e810-4103-bd23-392523dc0ac9)

If I run the same script from terminal the image then appear
```
sww query
----
eDP-1: 1920x1080, scale: 1, currently displaying: image: /home/mrduarte/Pictures/Lenovo Wallpapers/cyber_box.jpg
----
```
Desktop screenshot:
![image](https://github.com/Horus645/swww/assets/68701049/03ee0fa0-e9ae-4962-8b91-ab9c05f99023)

Bellow is the set-displays-swayidle script:
```
#!/bin/zsh
#ADD TO HYPERLAND CONFIG: exec = $HOME/.config/hypr/set-displays-swayidle set_res

set -ex

##Starter Commands
laptop=eDP-1
external_display=HDMI-A-1
hyprctl -j monitors | grep -F -q $external_display && EXT_MONITOR=1 || EXT_MONITOR=0
POWER_ADAPTER=$(cat /sys/class/power_supply/ADP0/online)

#Set Refresh Rate & Time Values
[ $POWER_ADAPTER -eq 1 ] && refresh_rate="165hz" && time_1=300 && time_2=310 && time_3=600 || refresh_rate="96.012hz" && time_1=270 && time_2=280 && time_3=300

main() {
  #Verify if swayidle is running
  killall swayidle || true

  swww img "/home/mrduarte/Pictures/Lenovo Wallpapers/cyber_box.jpg" || true

	#Set display
  hyprctl keyword monitor $laptop,1920x1080@$refresh_rate,$laptop_ori,1,bitdepth,10,vrr,1
	hyprctl keyword monitor $external_display,preferred,$external_display_ori,1

  #Set Swayidle For Suspend
  ## GTKLock command
  swayidle -w \
	  timeout $time_1 'hyprctl dispatch dpms off' \
	  resume 'hyprctl dispatch dpms on' \
	  timeout $time_2 'lock' \
	  timeout $time_3 '$HOME/.config/hypr/set-displays-swayidle verify_player' \
	  before-sleep 'lock' &
}

case "$1" in
lid_close)
	[[ $EXT_MONITOR -eq 1 ]] && hyprctl keyword monitor "eDP-1, disable" || systemctl suspend
	;;
lid_open)
	[[ $EXT_MONITOR -eq 1 ]] && hyprctl keyword monitor $laptop,1920x1080@$refresh_rate,$laptop_ori,1,bitdepth,10 || true
	;;
verify_player)
	[[ $(playerctl -l -s) == "" || $(playerctl status) == "Paused" ]] && systemctl suspend
	;;
set_res)
	[[ $EXT_MONITOR -eq 1 ]] && hyprctl keyword monitor HDMI-A-1,preferred,$HDMI_A_1_ori,1 || hyprctl keyword monitor $laptop,1920x1080@$refresh_rate,$e_DP1_ori,1,bitdepth,10
	;;
*)
  main
	;;
esac
```

**Comment by Horus645** [comment] 2023-12-21 13:49
So, to confirm, the problem only happens if you try setting the image during startup?

**Comment by MrDuartePT** [comment] 2023-12-21 14:07
Yes

**Comment by Horus645** [comment] 2023-12-21 15:04
I don't think that's necessary, since this seems to be a similar problem to #144. It also happens on hyprland, and some people have managed to work around it by adding sleep calls in their scripts.

**Comment by MrDuartePT** [comment] 2023-12-21 15:46
Ok thanks I gonna try and report back. For now I think you can close as duplicate.

**Comment by LGFae** [comment] 2024-02-18 15:47
Closing as a duplicate of #144 for now.

**Closed by LGFae** 2024-02-18 15:47 UTC

**Comment by MrDuartePT** [comment] 2024-02-18 15:55
> Closing as a duplicate of #144 for now.

No problem the sleep was fine for me
