### ISSUE TITLE
Background broken after change with fractional scaling

### ISSUE THREAD

**Issue by baltitenger** [LGFae/swww#289] opened 2024-04-20 14:00 UTC
Everything works fine initially (even if I change the scale of an output), but after changing the background with `swww img`, the newly set background is messed up, seemingly each row of pixels is shifted left from the row above it.

Note that once an output had fractional scaling, the next `swww img` will break even if scale is restored to 1, only restarting swww-daemon can fix it.

**Comment by LGFae** [comment] 2024-04-20 17:04
Ah yes, this is actually a duplicate of #233.

Here's the fun part: try using a scale of `1.5`. To me, at least, the issue does not happen.

It only happens if I use a scale that's not 1 + negative power of two. So, for example, `1.25`,  `1.5` both work as expected.

If you can confirm this, then it means #233 is partially solved, and there is only this final thwart left.

**Comment by baltitenger** [comment] 2024-04-20 18:58
Yep, 1.25 seems to work fine. (I was using 1.3 before so not that far off)

**Comment by LGFae** [comment] 2024-04-20 19:08
It was a rounding problem. #290 fixes it completely.

**Closed** 2024-04-25 11:47 UTC
Labels: bug
