### ISSUE TITLE
swww doesn't set full screen wallpaper when using vertical monitor

### ISSUE THREAD

**Issue by sin1111yi** [LGFae/swww#287] opened 2024-04-18 10:48 UTC
I am using 2 monitors with hyprland as wm, and one of them is horizen and the other is vertical.

When I set wallpapers with swww later than commit `f2ea5a7 Version 0.9.0`, the img didn't fill the vertical monitor like this. I set hyprland option `disable_hyprland_logo` to false, in case to show the whole monitor range.

![image](https://github.com/LGFae/swww/assets/62805296/fc4f193c-379f-4720-820a-564b30ae5af3)

the cmd is
```bash
swww img $HOME/.wallpapers/v/jonny-mckenna-4igCpD-Lnfg-unsplash.jpg -o DP-3 --resize=fit
```

if i remove `--resize=fit` and keep it as default, here's the result

![image](https://github.com/LGFae/swww/assets/62805296/6078c293-e2fd-42d8-a1c3-2efc5d183e98)

I have to rollback to v0.9.0 to avoid this problem.

**Comment by LGFae** [comment] 2024-04-18 14:34
This is a duplicate of #275. Closing for now.

**Closed by LGFae** 2024-04-18 14:34 UTC
Labels: duplicate
