### ISSUE TITLE
[Bug] Parse error while reading events: The message is malformed and cannot be parsed

### ISSUE THREAD

**Issue by munnik** [LGFae/swww#180] opened 2023-10-31 08:31 UTC
After an update of `Hyprland` I can't run `swww` anymore. `swww init` fails with this message:

```
$  swww init --no-daemon
08:21:48 [INFO] (main) Initialization succeeded! Starting main loop...
[wayland-client] Parse error while reading events: The message is malformed and cannot be parsed
Error: "Event loop closed unexpectedly: other error during loop operation"
```

```
$  hyprctl version
Hyprland, built from branch  at commit ab5497a0c9e9269b1036a0bede42cbd0bbfd94b9  ().
Tag: 

flags: (if any)
debug
```

**Comment by Grz3hu** [comment] 2023-11-12 17:48
Can confirm, same error 
![image](https://github.com/Horus645/swww/assets/53978280/74dbb9d5-fdb9-4c6d-bfd2-0a72c82bc97c)
commit id: 9afdd61adeaf413afbe853dbc5fdf6853c8bde21

**Comment by Houndie** [comment] 2023-11-25 01:36
I ran into this error when using hyprland 0.32.3 with swww 0.7.3.  (Both from nixos-stable).  Updating to swww 0.8.1 fixed the issue for me.

**Comment by LGFae** [comment] 2024-04-27 20:12
This was almost certainly caused by a mismatch between wayland versions. It should be fixed by now.

**Closed by LGFae** 2024-04-27 20:12 UTC
Labels: bug
