### ISSUE TITLE
Error while compilin swww-daemon

### ISSUE THREAD

**Issue by MRPOZZIchanel** [LGFae/swww#234] opened 2024-03-22 15:04 UTC
Hello! I was trying to install swww via yay and on the post-stages(171/173) i got an error

Compiling swww-daemon v0.8.2 (/home/padlakun/.cache/yay/swww/src/swww-0.8.2/daemon)
error: non-binding let on a synchronization lock
   --> daemon/src/wallpaper.rs:146:21
    |
146 |         let (inner, _) = self.lock();
    |                     ^ this lock is not assigned to a binding and is immediately dropped
    |
    = help: consider immediately dropping the value using `drop(..)` after the `let` statement
    = note: `#[deny(let_underscore_lock)]` on by default
help: consider binding to an unused variable to avoid immediately dropping the value
    |
146 |         let (inner, _unused) = self.lock();
    |                     ~~~~~~~

error: could not compile `swww-daemon` (bin "swww-daemon") due to 1 previous error

EDIT: distro: Arch, kernel: cachyos-bore 6.8.1-3

**Comment by mxwmnn** [comment] 2024-03-22 15:53
Same

**Comment by MRPOZZIchanel** [comment] 2024-03-22 16:08
Also, if u will skip this error then new errors will pop up on another stages!

**Comment by LGFae** [comment] 2024-03-22 16:10
yeah, a rustc update caused this. I will look into publishing a new update to work around this. The problem is that I wanted to solve #233 before that.

**Comment by LGFae** [comment] 2024-03-23 00:33
Alright guys, version 0.9.0 is out, so I will be closing this for now.

**Closed by LGFae** 2024-03-23 00:33 UTC

**Comment by i-L1ke-Cheese** [comment] 2024-03-23 09:31
wait so has it been fixed or not yet?

**Comment by LunasShade** [comment] 2024-03-23 11:12
If you use swww-git and not the normal one via paru or yay it works ^^

**Comment by Andorreta** [comment] 2024-03-23 12:03
> Not fixed

Like @LunasShade  said. It's fixed, But the normal AUR package isn't using the latest version. So you need to use the GIT package :smile:
