### ISSUE TITLE
wallpaper is grayscaled and distorted

### ISSUE THREAD

**Issue by lon4231** [LGFae/swww#256] opened 2024-04-01 22:27 UTC
i recently reinstalled my system (arch linux / hyprland) and this happened
![swappy-20240401_192407](https://github.com/LGFae/swww/assets/142271303/d20ee6b9-f6bf-416e-b614-6913f267c4e8)

**Comment by LGFae** [comment] 2024-04-01 22:36
Duplicate of #233.

**Closed by LGFae** 2024-04-01 22:36 UTC

**Comment by lon4231** [comment] 2024-04-01 22:48
> Duplicate of #233.

tried everything on that post,did'nt work

**Comment by lon4231** [comment] 2024-04-02 16:49
> copy this into a file or a function so you can run it everytime needed
> 
> ```shell
> # query the current state of swww (query's exit code being 0 means swww is running)
> swww query > /dev/null
> # if swww's running, kill it
> if [ $? -eq 0 ] ; then
>     swww kill
> fi
> # start swww again in xrgb format (solves the greyscale issue) and disown the process
> # (detach it from current terminal)
> nohup swww-daemon --format xrgb &> /dev/null &disown
> ```
> 
> `swww-daemon --format xrgb` was indeed present in #233 and works, at least for me. keep updated !

thanks, now it works

**Comment by diogeek** [comment] 2024-04-02 16:53
perfect !
keep in mind this is merely a workaround, and you'll need to execute this with every system startup for as long as this is not fixed
