### ISSUE TITLE
Black background on login since 0.8.0 / 0.8.1

### ISSUE THREAD

**Issue by Yasuhan** [LGFae/swww#144] opened 2023-07-14 17:51 UTC
Hey

ever since the latest update (both 0.8 and 0.8.1) on login in to my session I am just greeted by a black background, instead of my own. After either manually using swww img or simply reloading my hyprland config the wallpaper appears though. 

This is what I got in my hyprland.conf

`exec = swww init`  

`exec = swww img ~/.config/hypr/bg.jpg`

And I don't think there's anything wrong with that, as simply reloading said config makes the bg appear as intended.

So far I've deleted the .cache/swww folder several times, as well as the swww.socket under /var/run.  Any other ideas how to fix this issue?

**Comment by Horus645** [comment] 2023-07-14 18:39
I have one idea: set an image, don't delete the cache, comment out your second `exec`, then try again. `swww` should automatically load the last image that was set before logging out.

Although, this configuration of yours should be working, specially if it worked before.

**Comment by Yasuhan** [comment] 2023-07-14 18:51
Sadly neither of those options worked for me. I'm just really confused because it worked before the update.

**Comment by o-dasher** [comment] 2023-07-14 19:23
Just bumping this to say the same is happening to me since like a week or so.

**Comment by Horus645** [comment] 2023-07-14 20:37
> Just bumping this to say the same is happening to me since like a week or so.

If it has been happening for a week, then it could be something other than `swww`, since the update were released just two days ago.

**Comment by OopsYao** [comment] 2023-07-15 07:28
Can confirm. I use `swww init --no-daemon` as a systemd service (as `swww init` does not work). And it seems that `swww init --no-daemon` (even run in a terminal without systemd) does not respect cache after v0.8.1.

I didn't try v0.8.0, and `swww init` does respect the cache if run in a terminal.

Hyprland on Arch linux with ker 6.4.3-arch1-1

**Comment by hekatonkheirex** [comment] 2023-07-15 21:26
> 
> EDIT:
> 
> Another idea is to merge those two commands into one:
> 
> ```
> exec = swww init && swww img ~/.config/hypr/bg.jpg
> ```
> 

I can confirm I have this command in my config and the wallpaper isn't loading at startup.

Also using latest Arch + Hyprland.

**Comment by PlasticSoup** [comment] 2023-07-16 18:28
Also Arch+Hyprland. Maybe the issue lies there? I have always called a script from hyprland.conf to start swww with a random picture. All images in "wallpapr" are animated gifs, I never tried loading static images or colors.

`swww init && swww img $(find ~/Pictures/wallpapr -type f | shuf -n 1)`

After this issues appeared, at login only the bottom "Hyprland" render would be displayed. `swww query` would show that the daemon was running but displaying color 000000 instead of a picture. Running `swww kill` then `swww init` would display whichever image was in the cache. Or running the above script after kill would show a new random image.

I tried multiple ways to call swww, but the issue persisted. Today I changed the script to:

`swww init`
`wait`
`swww img $(find ~/Pictures/wallpapr -type f | shuf -n 1)`

Now the intended behavior is observed. Most logins have a new image load immediately, however occasionally there will be a 3-5 second delay where the cached image is displayed unanimated.

I hope this is useful information. @Horus645 if any additional information or diagnostic steps would be helpful I'm happy to assist.

**Comment by Horus645** [comment] 2023-07-17 14:46
I am also on arch linux, and I've just installed Hyprland from pacman to test this.

All I did was add the line:

```
exec-once = swww init
```

And it appears to be working. It is loading the last gif I had set for that monitor.

I then changed it to `swww init && swww img some-img` and it stopped working, as you are all describing.

In other words, I can`t reproduce this using just `swww init`.

**Comment by Horus645** [comment] 2023-07-17 15:06
> Can confirm. I use swww init --no-daemon as a systemd service (as swww init does not work). And it seems that swww init --no-daemon (even run in a terminal without systemd) does not respect cache after v0.8.1.

This is unrelated, btw. The daemon is no longer responsible for loading the cache during initialization. Now, the client is the one who loads it when you call `swww init`. Loading the cache in the daemon during initialization was causing some annoying race conditions where we would try to load things before the all the wayland setup stuff had run, so I decided to nuke it. I did not think people relied on `swww-daemon` loading the cache itself during initialization, so I didn't even mark this as a breaking change. I apologize.

In any case, this should be an entirely separate issue.

**Comment by Horus645** [comment] 2023-07-17 15:26
I have just implement a `--no-cache` flag for `swww init`. I don't know if it will work as a workaround, but you can now try:

```
swww init --no-cache && swww img some-img
```

If this *still* doesn't fix it, then I'll honestly be a little baffled.

**Comment by Yasuhan** [comment] 2023-07-17 17:46
At least for me adding --no-cache to add fixes it and I now always get a background as soon as I login.

**Comment by MotalaTech** [comment] 2023-07-17 19:47
Hi! Same problem here after 0.8.0, 0.8.1 No wallpaper at login (black screen). Running Arch and soldoestech hyprv4.

**Comment by hekatonkheirex** [comment] 2023-07-17 22:59
One workaround I found is delaying the startup with `exec-once = sleep 8; swww init`

BTW I'm using the AUR version, @Horus645 are you the maintainer? the `swww-git` version is outdated a month ago. I changed to `swww` but still doesn't have the `--no-cache` command.

**Comment by Horus645** [comment] 2023-07-17 23:59
Get the git version, @hekatonkheirex . From my understanding it should always track the latest master, even though it is from months ago.

**Comment by hekatonkheirex** [comment] 2023-07-18 00:08
> Get the git version, @hekatonkheirex . From my understanding it should always track the latest master, even though it is from months ago.
> 
> EDIT: also the `--no-cache` is literally just from a few hours ago. The latest released version doesn't have it, only master.

The git version is 0.7.2
![screenshot_20230717_200704](https://github.com/Horus645/swww/assets/63484218/f24d2ec3-116b-48d6-8673-ef605dcc99fc)

**Comment by Horus645** [comment] 2023-07-18 01:18
No, that's just the package's version, not the actual software.

Look at the url it is referencing in the PKGBUILD. It *will* get the latest master. The git version always tracks master, regardless of what it is called in the AUR. I just downloaded the source to double check, and sure enough, it got the latest master.

**Comment by hekatonkheirex** [comment] 2023-07-18 02:36
Well, I give up. I just leave it with the `sleep 8; swww init` line. The git version gave me errors about `Cargo.lock`. Also tried building myself but the `--no-cache` didn't work either. But I'll keep lurking here if there's any news on how to properly implemented it, maybe there's some different scripts we are using right now.

**Comment by MotalaTech** [comment] 2023-07-18 10:35
> One workaround I found is delaying the startup with `exec-once = sleep 8; swww init`
> 
> BTW I'm using the AUR version, @Horus645 are you the maintainer? the `swww-git` version is outdated a month ago. I changed to `swww` but still doesn't have the `--no-cache` command.

Thank you!! exec-once = sleep 1; swww init solved it for now 🙂

**Comment by cperaza305** [comment] 2023-07-19 06:12
I've also had this same issue since I've updated to .8.1. Whenever I use the swww widget to switch between a light and dark mode, there is a significant delay between switches.I am not certain if this could be related, but my spotify app broke at the same time as I updated swww which causes plenty of playback issues.

**Comment by Horus645** [comment] 2023-07-19 13:39
>  Whenever I use the swww widget

I... I think you posted this in the wrong project. What `swww` widget are you talking about?

**Comment by lokesh-krishna** [comment] 2023-07-21 06:52
Will we see a new release when #150 is merged?

**Comment by rdbo** [comment] 2024-03-21 17:14
Just reporting here that I was also facing this issue when running `river` compositor on QEMU, also fixed by adding `-t none`

**Comment by LGFae** [comment] 2024-04-27 20:03
Everyone, I believe I've finally fixed this in the latest master. Anyone can feel free to reopen this issue if that is not the case.

**Closed** 2024-04-27 20:02 UTC

**Comment by celikj** [comment] 2024-05-03 23:22
I get gray wallpaper after resumung from suspend

**Comment by LGFae** [comment] 2024-05-03 23:26
@celikj that would be new issue, since it isn't right after login. It might be related to #270.
